### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by Mublin** [patolojiatlasi/patolojiatlasi.github.io#7]
I need help on how to use quarto for multilingual purpose @patolojiatlasi please

**Comment by sbalci** [comment]
Hi,
Please see discussions here:
https://github.com/quarto-dev/quarto-cli/discussions/739 and https://github.com/quarto-dev/quarto-cli/issues/275

**Comment by Mublin** [comment]
Can you explain to me more in details , im a junior developer

**Comment by sbalci** [comment]
First do a web page with quarto and then publish it with github pages. After learning those, learn how to use github actions to deploy a page. The rest is a bit cosmetics.

**Comment by Mublin** [comment]
I have done it already sir, then what’s next?

**Comment by sbalci** [comment]
https://github.com/patolojiatlasi/patolojiatlasi.github.io/blob/main/.github/workflows/Quarto-Render-Bilingual-Book-Push-Tweet-Updates.yml
